services:

  web-ui:
    depends_on:
      - user-links
    build:
      context: .
      dockerfile: ./web-ui/Dockerfile
    container_name: web-ui
    networks:
      - front-end-net
    ports:
# Single access point, not other ports can be opened
      - "8080:8080"

  user-links:
    depends_on:
      - user-links-db
    build:
      context: .
      dockerfile: ./user-links/Dockerfile
    container_name: user-links
    networks:
      - front-end-net
      - user-links-net
    environment:
      - DB_PASSWORD=${LINK_SHARE_DB_PASSWORD:?database password not set}

  user-links-db:
    image: postgres:18.4
    container_name: user-links-db
    networks:
      - user-links-net
    environment:
      POSTGRES_PASSWORD: ${LINK_SHARE_DB_PASSWORD:?database password not set}
    volumes:
      - ./user-links/init-db-base:/docker-entrypoint-initdb.d
      - user-links-volume:/var/lib/postgresql

volumes:
  user-links-volume:

networks:
  front-end-net:
    driver: bridge
  user-links-net:
    driver: bridge
